# Generated by Django 5.2.16 on 2026-10-08 02:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('short_name', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=60)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('lunch_at', models.TimeField(default=datetime.time(12, 30))),
                ('source', models.CharField(blank=True, max_length=300)),
                ('imported', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short', models.CharField(blank=True, max_length=40)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conference.conference')),
            ],
            options={
                'ordering': ['conference', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('group', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('poster_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conference.conference')),
            ],
            options={
                'ordering': ['conference', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=800)),
                ('text', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('authors', models.JSONField(default=list)),
                ('affiliations', models.JSONField(default=list)),
                ('search_text', models.TextField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='conference.conference')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstracts', to='conference.session')),
            ],
            options={
                'ordering': ['conference', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=800)),
                ('speaker', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(default='talk', max_length=16)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('abstract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='conference.abstract')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='conference.conference')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='conference.room')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='conference.session')),
            ],
            options={
                'ordering': ['conference', 'date', 'start', 'room__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('conference', 'name'), name='room_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('conference', 'code'), name='session_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='abstract',
            constraint=models.UniqueConstraint(fields=('conference', 'key'), name='abstract_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='talk',
            constraint=models.UniqueConstraint(fields=('conference', 'key'), name='talk_unique_key'),
        ),
    ]
