# Generated by Django 5.2.16 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conveners',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
