# Generated by Django 5.2.16 on 2026-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_session_conveners_talk_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
